version : 2
jobs:
  build:
    docker:
      - image : circleci/node:8.11-strectch
    working_directoy: ~/repo
    steps:
      - checkout
      - restore_cache:
        keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
          - run: yarn install
          - save_cache:
               paths:
                - node_modules
               key: v1-dependencies-{{ checksum "package.json" }}
          - run: echo Done
          - run: yarn test
          - run: Test Done!!